-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 11:03:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(40) NOT NULL,
  `Lastname` VARCHAR(30) NULL,
  `City` VARCHAR(30) NOT NULL,
  `NPA` INT NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NameRest.` VARCHAR(45) NOT NULL,
  `City` VARCHAR(30) NOT NULL,
  `NPA` INT NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Unities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Unities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(30) NOT NULL,
  `Categories_id` INT NOT NULL,
  `Unities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Category1_idx` (`Categories_id` ASC),
  INDEX `fk_Products_Unities1_idx` (`Unities_id` ASC),
  CONSTRAINT `fk_Products_Category1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `mydb`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_Unities1`
    FOREIGN KEY (`Unities_id`)
    REFERENCES `mydb`.`Unities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Suppliers_id` INT NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Providers_idx` (`Suppliers_id` ASC),
  CONSTRAINT `fk_Orders_Providers`
    FOREIGN KEY (`Suppliers_id`)
    REFERENCES `mydb`.`Suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products_has_Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products_has_Suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Products_id` INT NOT NULL,
  `Suppliers_id` INT NOT NULL,
  INDEX `fk_Products_has_Providers_Providers1_idx` (`Suppliers_id` ASC),
  INDEX `fk_Products_has_Providers_Products1_idx` (`Products_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Products_has_Providers_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Providers_Providers1`
    FOREIGN KEY (`Suppliers_id`)
    REFERENCES `mydb`.`Suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CommandeLines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CommandeLines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NOT NULL,
  `Peremption` DATE NULL,
  `Products_id` INT NOT NULL,
  `Orders_id` INT NULL,
  `OrderDate` DATE NULL,
  `ArrivalDate` DATE NULL,
  `ArrivalQuantity` INT NULL,
  INDEX `fk_Products_has_Orders_Orders1_idx` (`Orders_id` ASC),
  INDEX `fk_Products_has_Orders_Products1_idx` (`Products_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Products_has_Orders_Products1`
    FOREIGN KEY (`Products_id`)
    REFERENCES `mydb`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_Orders_Orders1`
    FOREIGN KEY (`Orders_id`)
    REFERENCES `mydb`.`Orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
